return {
  {
    'nvim-treesitter/nvim-treesitter',
    run = ':TSUpdate',
    opts = {
      compilers = {
        'gcc',
      },
      ensure_installed = {
        'bash',
        'c',
        'cmake',
        'comment',
        'css',
        'diff',
        'dockerfile',
        'dot',
        'fish',
        'git_rebase',
        'gitattributes',
        'gitcommit',
        'gitignore',
        'go',
        'gomod',
        'hcl',
        'html',
        'http',
        'javascript',
        'jq',
        'json',
        'jsonc',
        'lua',
        'luadoc',
        'luap',
        'make',
        'markdown_inline',
        'markdown',
        'mermaid',
        'python',
        'query',
        'regex',
        'ruby',
        'rust',
        'sql',
        'toml',
        'typescript',
        'vim',
        'vimdoc',
        'yaml',
      },
      autotag = {
        enable = true,
      },
      context_commentstring = {
        enable = true,
      },
      fold = {
        enable = true,
      },
      highlight = {
        enable = true,
        use_languagetree = true,
        additional_vim_regex_highlighting = false,
      },
      incremental_selection = {
        enable = true,
      },
      indent = {
        enable = true,
      },
      matchup = {
        enable = true,
      },
      rainbow = {
        enable = true,
        extended_mode = true,
        max_file_lines = nil,
      },
      separator = '-',
      sync_install = false,
    },
  },
}
