return {
  {
    "williamboman/mason.nvim",
    opts = {
      ensure_installed = {
        "biome",
        "codelldb",
        "css-lsp",
        "delve",
        "deno",
        "docker-compose-language-service",
        "dockerfile-language-server",
        "gofumpt",
        "goimports",
        "gomodifytags",
        "gopls",
        "html-lsp",
        "impl",
        "iferr",
        "jdtls",
        "json-lsp",
        "lua-language-server",
        "marksman",
        "rust-analyzer",
        "shfmt",
        "sqlls",
        "staticcheck",
        "stylelint-lsp",
        "tailwindcss-language-server",
        "terraform-ls",
        "typescript-language-server",
        "yaml-language-server",
      },
    },
  },
}
